kalpa:
  play:
    - name: "Create a file foo.txt"
      kalpa-execa:
        cmd: "touch"
        opts:
          - "foo.txt"
    - name: "Downloading a file"
      kalpa-execa:
        cmd: "curl"
        opts:
          - "https://wordpress.org/latest.zip"
          - "-olatest.zip"
    - name: "Uncompress a file"
      kalpa-execa:
        cmd: "unzip"
        opts:
          - "-o"
          - "latest.zip"
    - name: "Deleting latest.zip"
      kalpa-execa:
        cmd: "rm"
        opts:
          - "latest.zip"
          - "-f"
  __data:
    cwd: "/home/vagrant/d2/kalpa-modules/kalpa/examples"
